;;Phrase breaks on words
(define (add_word_feats ttd)
 (mapcar (lambda (x)
     (set! u (utt.load nil (format nil "festival/utts/%s.utt" (car x))))
     (set! wf (load (format nil "prosody_feats/%s.break" (car x)) t))
        (mapcar (lambda (w wf)
            (item.set_feat w (car wf) (cadr wf)))
            (utt.relation.items u 'Word) wf)
         (utt.save u (format nil "festival/utts/%s.utt" (car x)))) (load ttd t) ))
;;Prominence on syllables
(define (add_syl_feats ttd)
 (mapcar (lambda (x)
     (set! u (utt.load nil (format nil "festival/utts/%s.utt" (car x))))
     (set! wf (load (format nil "prosody_feats/%s.prom" (car x)) t))
        (mapcar (lambda (w wf)
            (item.set_feat w (car wf) (cadr wf)))
            (utt.relation.items u 'Syllable) wf)
         (utt.save u (format nil "festival/utts/%s.utt" (car x)))) (load ttd t) ))

;;Intensity peaks and valleys on phones
(define (add_phone_feats ttd)
 (mapcar (lambda (x)
     (set! u (utt.load nil (format nil "festival/utts/%s.utt" (car x))))
     (set! Ipf (load (format nil "prosody_feats/%s.Ipeak" (car x)) t))
     (set! Ivf (load (format nil "prosody_feats/%s.Ivalley" (car x)) t))
        (mapcar (lambda (Ip Ipf)
            (item.set_feat Ip (car Ipf) (cadr Ipf)))
            (utt.relation.items u 'Segment) Ipf)
         (mapcar (lambda (Iv Ivf)
            (item.set_feat Iv (car Ivf) (cadr Ivf)))
            (utt.relation.items u 'Segment) Ivf)
             
    (utt.save u (format nil "festival/utts/%s.utt" (car x)))) (load ttd t) ))
